### ISSUE TITLE
fzf' extension doesn't exist or isn't installed: loop or previous error loading module 'telescope._extensions.fzf'

### ISSUE THREAD

**Issue by crazycodestar** [nvim-telescope/telescope-fzf-native.nvim#90] opened 2022-12-06 11:24 UTC
Just for context I'm trying to set this up on windows

when I try `require('telescope').load_extension('fzf')`  and try to source the file `:so %` I get an error

```
Error detected while processing :source (no file):
E5108: Error executing lua ...lugged\telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: loop or previous error loading module 'telescope._extensions.fzf'
stack traceback:
        [C]: in function 'error'
        ...lugged\telescope.nvim/lua/telescope/_extensions/init.lua:10: in function 'load_extension'
        ...lugged\telescope.nvim/lua/telescope/_extensions/init.lua:62: in function 'load_extension'
        [string ":source (no file)"]:35: in main chunk
```

I have tried using both cmake and make to re-install telescope-fzf-native.nvim
I even tried the `make clean && make` from this [issue](https://github.com/LunarVim/LunarVim/issues/1804)

**Comment by luiz00martins** [comment] 2022-12-11 23:06
Same. I've installed `fzf` with scoop, and it's accessible from the powershell that is running `nvim`, but I still get the error.

**Comment by Conni2461** [comment] 2022-12-12 06:12
I am sorry, i dont have a windows machine to test anything but i think it might be a regression introduced with the last commit #87

#89 does things but i cant validate if that fixes the issue for you guys. It might just make things worse just like #87

**Comment by luiz00martins** [comment] 2022-12-12 07:38
@Conni2461 No biggie. Just ping me when #89 gets published, and I'll test it.

**Comment by luiz00martins** [comment] 2022-12-13 01:03
`make`, installed by `scoop`

**Comment by crazycodestar** [comment] 2022-12-13 07:09
@dev4s i'm also using `make` installed by scoop. I also tried `cmake`

**Comment by Conni2461** [comment] 2022-12-18 08:43
I would have loved if someone could have tried out #89 prior to merging but it is what it is.

I just merged the PR, can anyone confirm, that the issue is resolved. Thanks :)

**Comment by luiz00martins** [comment] 2022-12-18 08:51
@Conni2461 Yep, looks fixed to me. Thanks!

**Closed** 2023-01-06 15:02 UTC

**Comment by dyskette** [comment] 2023-11-13 01:05
I make the mistake of not having installed `make` and `mingw` when opening my pre-configured neovim... after installing them I didn't know what to do, but I found the directory where lazy keeps the files in `~\AppData\Local\nvim-data\lazy\telescope-fzf-native.nvim` and after executing `make` in that directory all is fine.

Thanks!

**Comment by MrShortcut** [comment] 2024-07-13 05:02
Delete in the AppData/Local/ folder NVIM-DATA and INSTALL Dependenncies

scoop install gcc
scoop install fd
scoop install make
scoop install cmake

Open Neovim Enjoy!
