### ISSUE TITLE
Strange and random segmentation faults

### ISSUE THREAD

**Issue by epixinvites** [nvim-telescope/telescope-fzf-native.nvim#67] opened 2022-04-27 14:16 UTC
Here's the backlog -> https://termbin.com/ml6x

**Comment by Conni2461** [comment] 2022-04-27 15:16
when did these segfaults happen? Are you using telescope at the time?

I only see `fzf-native` listed as `Module` not nowhere in the stacktrace, Any chance you can build neovim in `debug` or in `RelWithDebInfo`?

**Comment by epixinvites** [comment] 2022-04-28 02:30
These segfaults happen at random times, but it only happens when I continuously press <Down>, <Up>, <Left> or <Right>. Out of 50 times I do that around once it will crash

**Comment by Conni2461** [comment] 2022-04-30 10:26
cant reproduce.

I dont think this is a fzf-native issue? I need a stacktrace with symbols, if you can produce one. Also a neovim version, etc

**Comment by epixinvites** [comment] 2022-04-30 11:02
Crashes disappeared after unplugging telescope-fzf-native.nvim, seems like it had compatibility issues with some other plugin I had.

**Comment by Conni2461** [comment] 2022-04-30 11:17
also make sure you have a up to date build. You can just run `make clean && make` in the project dir.

I wont comment anymore until i have a coredump with symbols. Otherwise i dont have enough information

**Comment by epixinvites** [comment] 2022-04-30 11:21
alright, i'll try to catch the segfault again

**Comment by Conni2461** [comment] 2022-05-15 18:38
any luck?

**Comment by epixinvites** [comment] 2022-05-16 01:45
Can't reproduce it again, I updated all my plugins, luajit and neovim and it just went away.

**Comment by Conni2461** [comment] 2022-05-16 07:00
:laughing: I'll close this issue for now. If you see it again with more information, feel free to reopen :)

**Closed by Conni2461** 2022-05-16 07:00 UTC
